### ISSUE TITLE
please function instead of method

### ISSUE THREAD

**Issue by princemaple** [gillkyle/egghead-elixir#1]
![image](https://user-images.githubusercontent.com/1329716/78321536-ffd78200-75b7-11ea-88a4-259f082c25e4.png)

**Comment by gillkyle** [comment]
That's a good point, I think I made sure the terminology was consistent on later videos. I'll see what I can do about updating a published video.

**Comment by gillkyle** [comment]
Thanks for pointing this out @princemaple, just made the update on the video.
